---
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - '/'
      - '/.github/actions/**/*'
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
    open-pull-requests-limit: 5
